### ISSUE TITLE
TODO list for DC2 processing

### ISSUE THREAD

**Issue by joezuntz** [LSSTDESC/TXPipe#69]
TXTwoPointFourier
- [x] Read the metadata from the metadata file instead of the tomo file
- [x] Make noise match this: https://gist.github.com/joezuntz/de47c80aa56c625aca2aff709bc87edf
- [x] Remove apodizing at all for cosmic shear
- [x] Switch to getting input from tracer_metadata
- [x] Make masks for proportional to the sum of weights in each pixel
- [x] Generate noise estimate from randoms?
- [x] Apply metacalibration factors

Maps & Masks
- [x] Make a fake map generator to test things (full sky, constant depth)
- [x] Use bright source mask from bo_mask branch

Selector
- [x] Split TXSelector into TXSourceSelector and TXLensSelector
- [x] Use PDFs for LensSelector

Covariance
- [x] Covariance for correlation functions

**Comment by joezuntz** [comment]
This was completed a while ago
