### ISSUE TITLE
TODO list for plots and null tests

### ISSUE THREAD

**Issue by joezuntz** [LSSTDESC/TXPipe#71]
Early Tests & Plots
-------------------

These tests can be done at the start of the pipeline, just by looking at input data.

They all focus on the PSF.  There should be three star samples:
- PSF stars
- Reserved stars
- All certain stars

Tests we need are:

- [x] Rowe statistics
- [ ] PSF residual whisker plot (reserved stars) across FoV
- [x] Histogram of PSF size residuals
- [x] PSF size residual as function of magnitude

Intermediate Tests & Plots
--------------------------

These tests need some kind of calculated TXPipe intermediate or final quantities, often just the list of galaxies selected, sometimes tomographic bins, and sometimes other quantities.  Many of them require the reponse factors to be correctly included.

- [x] Alpha/beta fit of shear to PSF
- [ ] Mean shear plot across FoV
- [ ] Gamma_t/x around chip centres
- [x] Gamma_t/x around field centres
- [x] Gamma_t/x around stars
- [x] Gamma_t/x around random points
- [x] Correlations between lensing map and systematics maps
- [x] Dependence of source density and ellipticity on observing conditions
- [x] Dependence of source density and ellipticity on n_visit
- [x] Star-Galaxy correlation function
- [x] B-modes
- [x] B-mode mass aperture statistic
- [x] gamma_x around lenses
- [x] Difference in corr functions when split by S/N
- [x] Difference in corr functions when split by systematic quantities
- [x] Difference in corr functions when split by chip location
- [x] Difference in corr functions when split by chip number

**Comment by joezuntz** [comment]
It's ocurred to me that the best way to do correlation functions with size and SNR splits is to just re-run the entire pipeline with different cuts, since that will do everything including computing the new n(z) values.  So I'll call that complete.

**Comment by joezuntz** [comment]
I think we've concluded that FOV/chip plots are not that useful for LSST since the number of exposures is so much higher so everything averages down. So the remaining plots will not be that useful, and I'll close this ancient issue now!
